[colors.primary]
background = "#111018"
foreground = "#c3c3c5"

[colors.cursor]
text = "#111018"
cursor = "#c3c3c5"

[colors.vi_mode_cursor]
text = "#111018"
cursor = "#c3c3c5"

[colors.search.matches]
foreground = "#111018"
background = "#c3c3c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5f5b6f"
background = "#c3c3c5"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#111018"
red = "#445A90"
green = "#5D6984"
yellow = "#6E748E"
blue = "#897F98"
magenta = "#9C93AB"
cyan = "#CBB5BB"
white = "#c3c3c5"

[colors.bright]
black = "#5f5b6f"
red = "#445A90"
green = "#5D6984"
yellow = "#6E748E"
blue = "#897F98"
magenta = "#9C93AB"
cyan = "#CBB5BB"
white = "#c3c3c5"

[colors.dim]
black = "#c3c3c5"
red = "#445A90"
green = "#9C93AB"
yellow = "#6E748E"
blue = "#897F98"
magenta = "#5D6984"
cyan = "#CBB5BB"
white = "#5f5b6f"

