[colors]
background = '#1110188e'
black = '#111018'
blue = '#445A90'
cursor = '#c3c3c5'
cyan = '#5D6984'
foreground = '#c3c3c5'
green = '#6E748E'
magenta = '#897F98'
red = '#9C93AB'
tabs = '#c3c3c5'
tabs-active = '#CBB5BB'
white = '#c3c3c5'
yellow = '#c3c3c5'
dim-black = '#1110188e'
dim-blue = '#445A908e'
dim-cyan = '#5D69848e'
dim-foreground = '#c3c3c58e'
dim-green = '#6E748E8e'
dim-magenta = '#897F988e'
dim-red = '#9C93AB8e'
dim-white = '#CBB5BB8e'
dim-yellow = '#c3c3c58e'
light-black = '#445A90'
light-blue = '#5D6984'
light-cyan = '#6E748E'
light-foreground = '#897F98'
light-green = '#9C93AB'
light-magenta = '#CBB5BB'
light-red = '#c3c3c5'
light-white = '#445A90'
light-yellow = '#5D6984'
